---
apiVersion: v1
kind: Pod
metadata: 
  name: pod1
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"

#here onlu requests will be there when u describe then thatss the limit for this pod

---
apiVersion: v1
kind: Pod
metadata: 
  name: pod12
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

#here limits only mentioned but pod will take this as requests and the same is limits when u run describe command
