apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploydemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels: 
        app: zomato
    spec:
      containers:
        - name: cont1
          image: centos
          command: ["/bin/bash","-c","sleep 1000"]
          volumeMounts:
            - name: vo1
              mountPath: "/tmp/devops"
      volumes:
        - name: vo1
          persistentVolumeClaim:
            claimName: number
