---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: cont1
      image: centos
      ports:
        - containerPort: 80
      command: ["/bin/bash","-c","while true; do echo hello ;sleep 5 ; done"]
      volumeMounts:
        - name: flm-volume
          mountPath: "/tmp/devops"
    
    - name: cont2
      image: centos
      ports:
        - containerPort: 80
      command: ["/bin/bash","-c","while true; do echo hello ;sleep 5 ; done"]
      volumeMounts:
        - name: flm-volume
          mountPath: "/tmp/devops"
  
  volumes:
    - name: flm-volume
      hostPath: 
        path: /tmp/mydata
