---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: onevolume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0e7ba504ae9c34dbb
    fsType: ext4