---
apiVersion: v1
kind: Pod
metadata:
  name: ngnx-pod1
  labels:
    team: integrations
    app: todo
spec:
  containers:
    - name: cont1
      image: nginx:latest
      ports:
        - containerPort: 80
      
