---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: cont1
      image: narasimhasai95/weatherapp
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: svcweatherapp
spec:
  type: ClusterIP
  selector:
    env: prod
  ports:
    - port: 80  #we can give anything
      targetPort: 80 #from our pod port

---
apiVersion: v1
kind: Service
metadata:
  name: svcnodeportweatherapp
spec:
  type: NodePort
  selector:
    env: prod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # Port exposed on the node (range: 30000-32767)

---
apiVersion: v1
kind: Service
metadata:
  name: svclbweatherapp
spec:
  type: LoadBalancer
  selector:
    env: prod
  ports:
    - port: 80
      targetPort: 80
      