---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs 
  labels: 
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wapp
  template:
    metadata:
      name: pod1
      labels:
        app: wapp
    spec:
      containers:
        - name: cont1
          image: narasimhasai95/weatherapp
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  type: ClusterIP
  selector:
    app: wapp
  ports:
    - port: 80
      targetPort: 80