---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: wapprs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wapp
  template:
    metadata:
      name: wapp-pod1
      labels:
        app: wapp
    spec:
      containers:
        - name: cont1
          image: narasimhasai95/weatherapp
          ports:
           - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  type: LoadBalancer
  selector:
    app: wapp
  ports:
    - port: 80
      targetPort: 80
      