---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  persistentvolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vo1
    fstype: ext4