---
apiVersion: v1
kind: Pod
metadata:
  name: pod11
spec:
  containers:
    - name: cont1
      image: ubuntu
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 1000
      ports:
        - containerPort: 80
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 30
