---
apiVersion: v1
kind: Pod
metadata:
  name: pod11
spec:
  containers:
    - name: cont1
      image: narasimhasai95/weatherapp
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 30
        periodSeconds: 5
      