---
apiVersion: v1
kind: Pod
metadata: 
  name: pod131
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: value1
          valueFrom:
            secretKeyRef:
              key: port
              name: avengers
    