---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["configmaps","pods"]
    verbs: ["get,"list","watch","create"]
  - apiGroups: ["*"]
    resources: ["delpoyment"]
    verbs: ["delete"]