---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stagerole
  namespace: stage
rules:
  - apiGroups: ["*"]
    resources: ["pods","deployments"]
    verbs: ["get","list","watch","create","delete"]
    