---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-task
  template:
    metadata:
      labels:
        app: frontend-task
    spec:
      containers:
        - name: cont1
          image: narasimhasai95/frontreact
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backendservice:345/goals"
---
apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  type: LoadBalancer
  selector:
    app: frontend-task
  ports:
    - port: 80
      targetPort: 3000
