---
apiVersion: v1
kind: Pod
metadata:
  name: pod121
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: myvolume
          mountPath: "/envvalues"
          readOnly: true
  volumes:
    - name: myvolume
      configMap:
        name: sai