---
apiVersion: v1
kind: Pod
metadata: 
  name: pod1
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      env:
        - name: port
          valueFrom:
            configMapKeyRef:
              name: flm
              key: port
        - name: dbname
          valueFrom:
            configMapKeyRef:
              name: flm
              key: db

#kubectl create cm flm --from-literal=db=mysql --from-literal=port=3000