---
apiVersion: v1
kind: Pod
metadata: 
  name: pod1
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sai